"""change coefficients table

Revision ID: 17a2b6364e0a
Revises: 1bbe8061bb80
Create Date: 2025-06-22 20:33:40.539727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a2b6364e0a'
down_revision: Union[str, Sequence[str], None] = '1bbe8061bb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coefficients', sa.Column('is_positive', sa.Boolean(), nullable=False))
    op.drop_column('coefficients', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coefficients', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('coefficients', 'is_positive')
    # ### end Alembic commands ###
