"""Initial revision

Revision ID: f5f62077225b
Revises: 6bbc7d948f51
Create Date: 2025-06-19 20:24:24.993816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f62077225b'
down_revision: Union[str, Sequence[str], None] = '6bbc7d948f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coefficients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.Enum('FIRST_RESPONSE_TIME', 'NEXT_RESPONSE_TIME', 'POLITENESS_RATING', 'COMPETENCE_RATING', name='parametertype'), nullable=False),
    sa.Column('type', sa.Enum('POSITIVE', 'NEGATIVE', name='coefficienttype'), nullable=False),
    sa.Column('norm', sa.Float(), nullable=False),
    sa.Column('base', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shifts')
    op.drop_table('coefficients')
    # ### end Alembic commands ###
